export const SKILL_MAP = {
  javascript: ["javascript", "js"],
  react: ["react", "reactjs", "react.js"],
  nextjs: ["next", "nextjs", "next.js"],
  node: ["node", "nodejs", "node.js"],
  express: ["express", "expressjs", "express.js"],
  mongodb: ["mongodb", "mongo"],
  mysql: ["mysql"],
  prisma: ["prisma"],
  rest: ["rest", "restapi", "restful"],
  docker: ["docker"],
  kubernetes: ["kubernetes", "k8s"],
  git: ["git", "github"],
  mern: ["mern", "mernstack", "mern-stack"],
};
